name: Metrics
on:
  schedule: [{cron: "0 0 1 1 *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: rahulkhatri137
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: data, markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_size: 24
